# Generated by Django 4.2.23 on 2025-08-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Тип заявки')),
                ('name', models.CharField(max_length=30, verbose_name='Имя клиента')),
                ('date', models.DateField(verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_flat', models.CharField(max_length=10, verbose_name='id квартиры')),
                ('number', models.CharField(max_length=10, verbose_name='Номер квартиры')),
                ('number_on_floor', models.CharField(max_length=10, verbose_name='Номер на этаже')),
                ('complex', models.CharField(max_length=30, verbose_name='Комплекс')),
                ('id_complex', models.CharField(max_length=50, verbose_name='id комплекса')),
                ('house', models.CharField(max_length=50, verbose_name='Корпус')),
                ('id_house', models.CharField(max_length=50, verbose_name='id корпуса')),
                ('floor', models.CharField(max_length=10, verbose_name='Этаж')),
                ('section', models.CharField(max_length=10, verbose_name='Секция')),
                ('rooms', models.CharField(max_length=10, verbose_name='Комнат')),
                ('flat_type', models.CharField(max_length=30, verbose_name='Тип помещения')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('price_base', models.CharField(max_length=20, verbose_name='Базовая цена')),
                ('square', models.CharField(max_length=10, verbose_name='Площадь')),
                ('square_live', models.CharField(max_length=10, verbose_name='Площадь жилая')),
                ('square_hook', models.CharField(max_length=10, verbose_name='Площадь кухни')),
                ('status', models.CharField(max_length=10, verbose_name='Статус')),
                ('decoration', models.CharField(max_length=10, verbose_name='Отделка')),
                ('plan', models.CharField(default='', max_length=250, verbose_name='Планировка')),
                ('floor_plan', models.CharField(default='', max_length=250, verbose_name='Поэтажка')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
