# Generated by Django 4.2.23 on 2025-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='id',
        ),
        migrations.AlterField(
            model_name='flat',
            name='id_flat',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
