# Generated by Django 4.2.23 on 2025-08-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_flat_id_alter_flat_id_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='id_flat',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID квартиры'),
        ),
    ]
