# Generated by Django 4.2.23 on 2025-08-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_flat_id_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='complex',
            field=models.CharField(default='', max_length=30, verbose_name='Комплекс'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='decoration',
            field=models.CharField(default='', max_length=10, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_type',
            field=models.CharField(default='', max_length=30, verbose_name='Тип помещения'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.CharField(default='', max_length=10, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='house',
            field=models.CharField(default='', max_length=50, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='id_complex',
            field=models.CharField(default='', max_length=50, verbose_name='id комплекса'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='id_house',
            field=models.CharField(default='', max_length=50, verbose_name='id корпуса'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.CharField(default='', max_length=10, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='number_on_floor',
            field=models.CharField(default='', max_length=10, verbose_name='Номер на этаже'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.CharField(default='', max_length=20, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price_base',
            field=models.CharField(default='', max_length=20, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.CharField(default='', max_length=10, verbose_name='Комнат'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='section',
            field=models.CharField(default='', max_length=10, verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='square',
            field=models.CharField(default='', max_length=10, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='square_hook',
            field=models.CharField(default='', max_length=10, verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='square_live',
            field=models.CharField(default='', max_length=10, verbose_name='Площадь жилая'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='status',
            field=models.CharField(default='', max_length=10, verbose_name='Статус'),
        ),
    ]
